"""Ports defining contracts implemented by external providers and engines."""

from .errors import (
    ProviderAuthenticationError,
    ProviderCapabilityError,
    ProviderDataError,
    ProviderError,
    ProviderErrorCode,
    ProviderMappingError,
    ProviderRateLimitError,
    ProviderUnavailableError,
)
from .optimisation import OptimisationEngine, OptimisationError, OptimisationErrorCode
from .persistence import (
    CanonicalDatasetName,
    CanonicalRepository,
    CanonicalSnapshot,
    DatasetArtifact,
    DecisionRunRepository,
    ImmutableRegistrationConflict,
    PersistenceError,
    SnapshotCatalog,
    SnapshotRegistration,
    SourceObjectHash,
    UnsupportedSchemaVersion,
)
from .providers import (
    LeagueProvider,
    ManagerStateProvider,
    NewsEvidenceProvider,
    PlayerDataProvider,
    ProjectionProvider,
)
from .run_records import (
    InvalidPreviousRunReference,
    InvalidRunRecord,
    InvalidRunStateTransition,
    InvalidStageTransition,
    RunRecordConflict,
    RunRecordError,
    RunRecordNotFound,
    RunRecordRepository,
)
from .types import (
    Freshness,
    ProviderCapability,
    ProviderDescriptor,
    ProviderProvenance,
    ProviderResponse,
)

__all__ = [
    "CanonicalDatasetName",
    "CanonicalRepository",
    "CanonicalSnapshot",
    "DatasetArtifact",
    "DecisionRunRepository",
    "ImmutableRegistrationConflict",
    "InvalidPreviousRunReference",
    "InvalidRunRecord",
    "InvalidRunStateTransition",
    "InvalidStageTransition",
    "PersistenceError",
    "Freshness",
    "LeagueProvider",
    "ManagerStateProvider",
    "NewsEvidenceProvider",
    "OptimisationEngine",
    "OptimisationError",
    "OptimisationErrorCode",
    "PlayerDataProvider",
    "ProjectionProvider",
    "ProviderAuthenticationError",
    "ProviderCapability",
    "ProviderCapabilityError",
    "ProviderDataError",
    "ProviderDescriptor",
    "ProviderError",
    "ProviderErrorCode",
    "ProviderMappingError",
    "ProviderProvenance",
    "ProviderRateLimitError",
    "ProviderResponse",
    "ProviderUnavailableError",
    "RunRecordConflict",
    "RunRecordError",
    "RunRecordNotFound",
    "RunRecordRepository",
    "SnapshotCatalog",
    "SnapshotRegistration",
    "SourceObjectHash",
    "UnsupportedSchemaVersion",
]
