"""Application use cases and orchestration."""

from .analytical_artifacts import AnalyticalArtifactService
from .analytical_history import (
    AnalyticalHistoryError,
    AnalyticalHistoryResult,
    AnalyticalHistoryService,
    ComparisonGenerator,
    HistoryGenerator,
    RecommendationChange,
    classify_recommendation_change,
)
from .availability import apply_availability_exclusions, assess_availability
from .decision_bundles import (
    DecisionBundleArtifact,
    DecisionBundleError,
    build_decision_bundle,
    load_decision_bundle,
    parse_decision_bundle,
    serialize_decision_bundle,
    write_decision_bundle,
)
from .doctor import (
    DiagnosticCheck,
    DiagnosticStatus,
    DoctorReport,
    DoctorService,
)
from .evaluation_artifacts import (
    DecisionEvaluationArtifact,
    serialize_decision_evaluation,
    write_decision_evaluation,
)
from .gameweek_evidence import (
    EvidenceComponentBytes,
    EvidenceDriftError,
    GameweekEvidenceArtifact,
    InvalidEvidenceManifest,
    ProjectionEvidenceInput,
    SnapshotEvidenceInput,
    build_gameweek_evidence_manifest,
    load_gameweek_evidence_artifact,
    parse_gameweek_evidence_manifest,
    serialize_gameweek_evidence_manifest,
    snapshot_content_sha256,
    validate_gameweek_evidence,
    validate_gameweek_evidence_references,
    write_gameweek_evidence_manifest,
)
from .lineup_evidence_evaluation import (
    LineupEvidenceStatisticalEvaluator,
    records_from_joined,
)
from .lineup_evidence_validation import build_lineup_evidence_observation
from .lineup_outcomes import (
    assess_chronology_input,
    assess_observation_chronology,
    join_lineup_outcomes,
    valid_joined_outcomes,
)
from .orchestration import (
    BASELINE_STAGE,
    DOCTOR_STAGE,
    EVIDENCE_STAGE,
    OPERATOR_EXECUTION_CONFIRMATION_STAGE,
    ORCHESTRATOR_STAGES,
    POST_SUBMISSION_VERIFY_STAGE,
    PRE_SUBMISSION_VERIFY_STAGE,
    BaselineOutcome,
    GameweekOrchestrator,
    OrchestratorError,
    OrchestratorInputError,
    OrchestratorRequest,
    OrchestratorResult,
    OrchestratorResumeError,
)
from .planning import compare_planning_horizons, persist_planning_decision_run
from .scenario_lifecycle import (
    ScenarioLifecycleError,
    prepare_scenario_candidate,
    promote_scenario_candidate,
    review_scenario_candidate,
    serialize_frozen_scenario,
    write_frozen_scenario,
)
from .scenarios import (
    ScenarioConstraintInput,
    ScenarioDefinitionInput,
    ScenarioErrorCode,
    ScenarioValidationError,
    parse_scenario_definition,
)
from .squad_runs import persist_squad_decision_run
from .submission_safety import (
    SUBMISSION_SAFETY_ARTEFACT_KIND,
    SUBMISSION_SAFETY_SCHEMA_VERSION,
    PreviousReconciliation,
    SafetyStatus,
    SubmissionSafetyArtifact,
    SubmissionSafetyArtifactError,
    SubmissionSafetyResult,
    load_submission_safety_result,
    plan_submission,
    serialize_submission_safety_result,
    verify_submission,
    write_submission_safety_result,
)
from .transfer_candidates import (
    EvaluatedTransferCandidate,
    TransferCandidate,
    enumerate_and_rank,
    enumerate_transfer_candidates,
    rank_transfer_candidates,
)
from .transfer_runs import persist_transfer_decision_run

__all__ = [
    "AnalyticalArtifactService",
    "build_lineup_evidence_observation",
    "LineupEvidenceStatisticalEvaluator",
    "records_from_joined",
    "assess_chronology_input",
    "assess_observation_chronology",
    "join_lineup_outcomes",
    "valid_joined_outcomes",
    "AnalyticalHistoryError",
    "AnalyticalHistoryResult",
    "AnalyticalHistoryService",
    "ComparisonGenerator",
    "DecisionBundleArtifact",
    "DecisionBundleError",
    "DecisionEvaluationArtifact",
    "HistoryGenerator",
    "RecommendationChange",
    "classify_recommendation_change",
    "load_decision_bundle",
    "parse_decision_bundle",
    "DiagnosticCheck",
    "DiagnosticStatus",
    "DoctorReport",
    "DoctorService",
    "EvidenceComponentBytes",
    "EvidenceDriftError",
    "GameweekEvidenceArtifact",
    "GameweekOrchestrator",
    "InvalidEvidenceManifest",
    "ProjectionEvidenceInput",
    "SnapshotEvidenceInput",
    "apply_availability_exclusions",
    "assess_availability",
    "build_decision_bundle",
    "build_gameweek_evidence_manifest",
    "load_gameweek_evidence_artifact",
    "compare_planning_horizons",
    "persist_planning_decision_run",
    "persist_squad_decision_run",
    "parse_gameweek_evidence_manifest",
    "persist_transfer_decision_run",
    "serialize_decision_bundle",
    "serialize_decision_evaluation",
    "serialize_gameweek_evidence_manifest",
    "snapshot_content_sha256",
    "validate_gameweek_evidence",
    "validate_gameweek_evidence_references",
    "write_decision_bundle",
    "write_decision_evaluation",
    "write_gameweek_evidence_manifest",
    "SUBMISSION_SAFETY_ARTEFACT_KIND",
    "SUBMISSION_SAFETY_SCHEMA_VERSION",
    "PreviousReconciliation",
    "SafetyStatus",
    "SubmissionSafetyArtifact",
    "SubmissionSafetyArtifactError",
    "SubmissionSafetyResult",
    "load_submission_safety_result",
    "plan_submission",
    "serialize_submission_safety_result",
    "verify_submission",
    "write_submission_safety_result",
    "BASELINE_STAGE",
    "DOCTOR_STAGE",
    "EVIDENCE_STAGE",
    "OPERATOR_EXECUTION_CONFIRMATION_STAGE",
    "ORCHESTRATOR_STAGES",
    "POST_SUBMISSION_VERIFY_STAGE",
    "PRE_SUBMISSION_VERIFY_STAGE",
    "BaselineOutcome",
    "OrchestratorError",
    "OrchestratorInputError",
    "OrchestratorRequest",
    "OrchestratorResult",
    "OrchestratorResumeError",
    "ScenarioConstraintInput",
    "ScenarioDefinitionInput",
    "ScenarioErrorCode",
    "ScenarioValidationError",
    "parse_scenario_definition",
    "ScenarioLifecycleError",
    "prepare_scenario_candidate",
    "promote_scenario_candidate",
    "review_scenario_candidate",
    "serialize_frozen_scenario",
    "write_frozen_scenario",
    "EvaluatedTransferCandidate",
    "TransferCandidate",
    "enumerate_and_rank",
    "enumerate_transfer_candidates",
    "rank_transfer_candidates",
]
